"""Created column for temp table

Revision ID: 23596d812a88
Revises: 33cc0e106846
Create Date: 2022-07-06 21:02:35.061892

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '23596d812a88'
down_revision = '33cc0e106846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Temp', sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Temp', 'created')
    # ### end Alembic commands ###
